services:
  mobile:
    image: bank-sampah-mobile:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://202.10.42.82/api}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://202.10.42.82/api}
    ports:
      - "${APP_PORT:-3000}:3000"
